# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TestProcessingPlugin
                                 A QGIS plugin
 TestProcessingPlugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-27
        copyright            : (C) 2021 by QGIS Vanguard
        email                : li_hengshan@sla.gov.sg
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'QGIS Vanguard'
__date__ = '2021-04-27'
__copyright__ = '(C) 2021 by QGIS Vanguard'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TestProcessingPlugin class from file TestProcessingPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TestProcessingPlugin import TestProcessingPluginPlugin
    return TestProcessingPluginPlugin()
