# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PythonSpatialAnalysis
                                 A QGIS plugin
 The plugin use PYSAL for spatial analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-26
        copyright            : (C) 2021 by Singapore Land Authority
        email                : li_hengshan@sla.gov.sg
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PythonSpatialAnalysis class from file PythonSpatialAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Python_Spatial_Analysis import PythonSpatialAnalysis
    return PythonSpatialAnalysis(iface)
